### ISSUE TITLE
Initial Task List

### ISSUE THREAD

**Issue by nkabz** [nkabz/promote-api#1]
# Challenge :1st_place_medal: 
**Checklist:**

- [x] Promote API :star2: 

# Docker :whale:
**Checklist:**

- [x] Initial Setup and Config

# Database :dolphin: 
**Checklist:**

- [x] Structure 

# Back-end :elephant: 
**Checklist:**

- [x] Structure 

- [x] Database
  - [x] Migrations
  - [x] Models
  - [x] Factories
  - [x] Seeders

- [x] API
  - [x] Routes
    - [x] Comment in a post
    - [x] List all comments from a post
    - [x] List all comments from a user
    - [x] Get notifications from a user
    - [x] Delete a comment
  - [x] Pagination
  - [x] Auth

- [x] Notifications

# Documentation :writing_hand:
**Checklist:**

 - [x] Setup
 - [x] API
